---
-
  file:
    group: "{{ nginx_user }}"
    mode: 448
    owner: "{{ nginx_user }}"
    path: "{{ app_root }}"
    state: directory
  name: "Create application directory"
  tags:
    - create_app_directory

-
  git:
    accept_hostkey: true
    dest: "{{app_root}}/"
    #key_file: "{{ nginx_ssh_root }}/id_rsa"
    repo: "{{ repo_url }}"
    version: "{{ git_branch }}"
  name: "Clone uvdesk code repository"
  tags:
    - add_uvdesk_repo