---
# Dependency
test_required_libs:
    - wget
    - software-properties-common
    - net-tools
    - unzip

# Nginx Configurations
nginx_config_dir: /etc/nginx
nginx_user: www-data
nginx_home_dir: /var/www
nginx_ssh_root: "{{ nginx_home_dir }}/.ssh"

app_config_path: "{{ nginx_config_dir }}/sites-available/default"
app_config_path_link: /etc/nginx/sites-enabled/default

access_log: /var/log/nginx/access.log
error_log: /var/log/nginx/error.log
nginx_file_upload_limit_mb: 3

# Web Application and wordpress Configurations
app_root: "{{ nginx_home_dir }}/app"

# PHP config varaibles
fastcgi_pass: unix:/run/php/php7.2-fpm.sock
php_ini_config_file: /etc/php/7.2/fpm/php.ini

# BB Repo Url
git_branch: master
repo_url: https://github.com/uvdesk/community-skeleton.git
