---
# Dependency
test_required_libs:
    - wget
    - software-properties-common
    - net-tools
    - openssh-client
    - unzip

# Nginx Configurations
nginx_config_dir: /etc/nginx
nginx_user: www-data
nginx_home_dir: /var/www
nginx_ssh_root: "{{ nginx_home_dir }}/.ssh"

app_config_path: "{{ nginx_config_dir }}/sites-available/default"
app_config_path_link: /etc/nginx/sites-enabled/default

access_log: /var/log/nginx/access.log
error_log: /var/log/nginx/error.log
nginx_file_upload_limit_mb: 11
ssh_private_key: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFb3dJQkFBS0NBUUVBcldlVEwxYmxtTm9sdmZNcWl4NmxkamlQbmcrR3F2NG0ycmdPZ2lCeVFZdUNPWGNLCndaSDFHYlV4U3FnQUJEZjBQaFQzdXZhZmc2NjduOU9NVzdISG1iZ2xzQ25KOUdIUUZsRTlCaHhGUGJPV1AxL1YKelVnYWM5WVRwVVhwcjFXT1VzUDdJNzNlY0VqU0oxRWlaSXFwYVJraUZRM1daRURvOUtsNm1ZQ0FOc3hvOG5QRAovT2dRRWkvNUhpYXBjT2orb2FBUGxhMEM1eHRZSXBqcnUvYzd3aGpBa2M2ekxrVHhKVFhqOFFlTnQzTkZFa0FYCkpkVEJTcHFjOHZvWUh2VXZFamMyRGM0THhGMVhxSVd6QUFxV1FiR2U5RDNyYzZRdVpwWTBXT0o5UkttMzZvc3cKMXJrQmEraXNPNjNWY25QQXdSNmJYdnQyV1hua0FaTU9Ja3ZLWFFJREFRQUJBb0lCQUhOTm5lY3FodnorZ1g0dgpCU2tBdGRGSWh1YjVOL2pYaW9xQlBOUjJNc00ydXQ3dk15M0htZzBBR01pbHNXMGNyOEhnTzJJTXY4RFdIVmlICldKdFlPWHNUb2F2ai9iQU1va3RVdFprc2p6WWFCbHdabzVjZXpNZ2RuMjZVY0hEd0dQVWI4QkN5SGdqWHd6WDEKazBMN21PNlRrY0FpTlY3d2NuYk5nd0l6R2c1VkFYZi8zMDN0aElQcEFDZ2prcEVjWmx0bnVJdDQrRkZQNzB3SQpOTTlLdVEvY1BaNUtRZ0hEalh0U3ovYjhiN3lTS00vTnRkWklTOCs4emRWblIyZWliVUpVOCt5cXNFdVpDcnVwCkVkaTNCWWlNS1EydFBHQWlTMi8xMG9pUmNLelBjb2hnUDRndndGa05iK1dnYW1VenB0Vkw3cS9DaWNuVENaemgKaXErRjVvRUNnWUVBMDVqRXowT2VBM29OdWdmREdBbWhNdFJkRGVONUs0eFh3dGJ1bVFQTm9EU0tzMHF3TFM4ZQpCbUU1OGNCUkV1MVhjZXo0UlA1OG1YdFJGOEtMOE4wTFlEZUFZc1NQUitUd0pGeThrUkFPSlFabU1Mem91QVprCjMyV050ZmpyQkc1dDZpZC82MkFsVEZmNjQ2d2ZCUk5leUJFUzZST29CUlFXUWJVOTJKdTVUZTBDZ1lFQTBjc1QKelZlWFVmREZmTUJqTXhvQVZHdStnMDM1WnhjNm52Y1pQYTRHbmV3K201MUpsL3YrZmpZQnh4dVM3RHQ4MUJ2NAo1SmFHV2lwNnpGMGEraUxCZmVZaUM2OE1EUE05UmlrdmxsQWluUTdma0p0SHYzZWtLanBmZFFzNGtQSEZ6TmkwClprQ1NJVHdmcEF6Y0VGWGgwOTlSd1pIZkxUSG5pRGM4ak9XbllERUNnWUI4Tk9MaVgyaXoxY09VL2RWeG1NVjkKRnRlQXZaUjFFYTY2ZW53WWFma2NIM3VEZjBZblg4OGFJNXhsNG1RMDNnbEVvTHVqbEZjRHFUV1M0dXBPZXhLZwphalA4eGpEdEhPQXlHQlhBZVZJMFBhdGkxS0V1MU9JRm1KRTB6bWIyZFBRa1RRZHozVDVIc0NWZjI3dGh1VnNiCnlabjJJMG12b1hqbkhVS3VrY3FXaVFLQmdRRFF4bnFQVjhLRHpjcUthbDZONVNzODEvaEFiU0ZzSVNhNk9ZY0oKNVp3NkhuYnpuNlEwTnBjOWZIdHFiSnRhc1p4NDdObFVpaU5ycVdpSTVZTEtPRG84RXdBQWhwUEVjMitmMmE2OAp0RVN0N2JZNER2OW9vQ1JqemJGZkplcUYrOFJ2Slp6cFFRcnJQZ3p5MGNWU0VGVnE1b3RTeWRyQi9DN0FWTS9TCkcxemtrUUtCZ0RCWTZ1VURpTnhvTUtrVi9FUjdpV1NQTmhNSURicnAybmVXc3ljZnZ2YjRSNUEyRWRuUVdPNGYKQWhKR240U0VzSUV5b2NpSEljckpmU1B4QXY3R0lsMm5qZjN3WCtKTHZVQ0h4dG4vQk45SWVheXkzbWk2YWZ5LwpWTVZCeUtWcjNDcmFaQlpOcG1VTGVMWlpIOC9UNW5TWmxIYnFsRGZld21nbjJKMVdYd09lCi0tLS0tRU5EIFJTQSBQUklWQVRFIEtFWS0tLS0tCg==

# Web Application and wordpress Configurations
app_root: "{{ nginx_home_dir }}/app"

# PHP config varaibles
fastcgi_pass: unix:/run/php/php7.2-fpm.sock
php_ini_config_file: /etc/php/7.2/fpm/php.ini

# BB Repo Url
git_branch: master
repo_url: git@bitbucket.org:carbanglateam/theme-carbangla.git
